### ISSUE TITLE
Handle unsupported file formats better

### ISSUE THREAD

**Issue by TheDuchy** [CERT-Polska/karton-classifier#40]
karton-classifier_1         | [2022-01-11 20:00:21,926][INFO] Received new task - 04eeb477-cd10-4465-895e-321526ddcd90
karton-classifier_1         | [2022-01-11 20:00:22,007][WARNING] Heuristics disabled - unknown encoding
karton-classifier_1         | [2022-01-11 20:00:22,008][INFO] Sample b'1640812552158.gif' not recognized (unsupported type)

While unpacking a zip containing a .gif file the file got tossed, I suggest that the file should be uploaded anyways and appropriate relations should be created even though the file is not tagged.

**Comment by ITAYC0HEN** [comment]
I second this opinion. We're facing more and more artifacts that aren't making it to MWDB. This is because Classifier set their stage to "unrecognized" and therefore mwdb-reporter won't report this file to mwdb (it only binds to recognized samples).

A recent example is the encrypted form of [CaddyWiper](https://www.welivesecurity.com/2022/04/12/industroyer2-industroyer-reloaded/#:~:text=9CE1491CE69809F92AE1FE8D4C0783BD1D11FBE7) ([9CE1491CE69809F92AE1FE8D4C0783BD1D11FBE7](https://www.virustotal.com/gui/file/1724a0a3c9c73f4d8891f988b5035effce8d897ed42336a92e2c9bc7d9ee7f5a/details) ) From ESET's report. It happened before with shellcodes and other artifacts.

**Comment by nazywam** [comment]
Would a opt-in "--report-all" option work? We should also consider switching permanently though 🤔

**Comment by ITAYC0HEN** [comment]
yeah, will be better. Even by default imo

**Comment by middleware99** [comment]
> Would a opt-in "--report-all" option work? We should also consider switching permanently though 🤔

how about extending filters on mwdb-reporter using cli parameters, to be like that?
```python
    filters = [
        {"type": "sample", "stage": "recognized"},
        {"type": "sample", "stage": "analyzed"},
        {"type": "sample", "stage": "unrecognized"},
        {"type": "config"},
        {"type": "blob"},
    ]
```

or this one (I suppose its similar):

```python
    filters = [
        {"type": "sample"},
        {"type": "config"},
        {"type": "blob"},
    ]
```

does it affect backend side or cause any other problems?

**Comment by Harri-Renney** [comment]
Agreed. Please pass through a file to be analysed but other Karton tasks despite classifier having an issue identifying it.

**Comment by nazywam** [comment]
Seeing as this is an issue more related to reporter itself (classifier already reports unrecognized files) moving this over to the reporter repository: https://github.com/CERT-Polska/karton-mwdb-reporter/issues/31
